/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrepareRouteImport } from './routes/prepare'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as UnderstandRouteImport } from './routes/understand'
import { Route as SafetyProfileRouteImport } from './routes/safety.profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepareRoute = PrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UnderstandRoute = UnderstandRouteImport.update({
  id: '/understand',
  path: '/understand',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyProfileRoute = SafetyProfileRouteImport.update({
  id: '/safety/profile',
  path: '/safety/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prepare': typeof PrepareRoute
  '/profile': typeof ProfileRoute
  '/understand': typeof UnderstandRoute
  '/safety/profile': typeof SafetyProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prepare': typeof PrepareRoute
  '/profile': typeof ProfileRoute
  '/understand': typeof UnderstandRoute
  '/safety/profile': typeof SafetyProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prepare': typeof PrepareRoute
  '/profile': typeof ProfileRoute
  '/understand': typeof UnderstandRoute
  '/safety/profile': typeof SafetyProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prepare' | '/profile' | '/understand' | '/safety/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prepare' | '/profile' | '/understand' | '/safety/profile'
  id:
    | '__root__'
    | '/'
    | '/prepare'
    | '/profile'
    | '/understand'
    | '/safety/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrepareRoute: typeof PrepareRoute
  ProfileRoute: typeof ProfileRoute
  UnderstandRoute: typeof UnderstandRoute
  SafetyProfileRoute: typeof SafetyProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prepare': {
      id: '/prepare'
      path: '/prepare'
      fullPath: '/prepare'
      preLoaderRoute: typeof PrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/understand': {
      id: '/understand'
      path: '/understand'
      fullPath: '/understand'
      preLoaderRoute: typeof UnderstandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/profile': {
      id: '/safety/profile'
      path: '/safety/profile'
      fullPath: '/safety/profile'
      preLoaderRoute: typeof SafetyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrepareRoute: PrepareRoute,
  ProfileRoute: ProfileRoute,
  UnderstandRoute: UnderstandRoute,
  SafetyProfileRoute: SafetyProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
